swagger: '2.0'
info:
  version: '1.0'
  title: RBKmoney URL-shortener API
  termsOfService: 'http://rbkmoney.com/'
  contact:
    name: RBKmoney support team
    email: tech-support@rbkmoney.com
    url: 'https://api.rbk.money'
  description: |
    URL-shortener API 
schemes:
  - https
consumes:
  - application/json; charset=utf-8
produces:
  - application/json; charset=utf-8
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
    description: >
      Для аутентификации вызовов мы используем [JWT](https://jwt.io).
      Cоответствующий ключ передается в заголовке.
      ```shell
       Authorization: Bearer {TOKENIZATION|PRIVATE_JWT}
      ```
      Посмотреть ваш API-ключ вы можете в [личном
      кабинете](https://dashboard.rbk.money/api/key).
      Ключи не разделяются на тестовые и боевые, ваш API ключ открывает доступ
      ко всем функциям платформы. Для тестовых транзакций используйте ID
      тестовых магазинов.
      Помните, что вы никому не должны передавать ваш API ключ!
security:
  - bearer: []
responses:
  NotFound:
    description: Entity not found
    schema:
      $ref: '#/definitions/GeneralError'
  BadRequest:
    description: Illegal input for operation
    schema:
      $ref: '#/definitions/LogicError'
parameters:
  requestID:
    name: X-Request-ID
    in: header
    description: Уникальный идентификатор запроса к системе
    required: true
    type: string
    maxLength: 32
    minLength: 1
  shortUrl:
    name: shortUrl
    in: path
    description: Короткая ссылка
    required: true
    type: string
    format: url
tags:
  - name: Shortener 
    x-displayName: Короткие ссылки
    description: Получение и работа с короткими ссылками
